spring.application.name=locadora-videogames
spring.datasource.url=jdbc:h2:mem:locadora
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# VULNERABILIDADE: Stack trace exposto
server.error.include-stacktrace=always
server.error.include-message=always

# CORS permissivo
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=*
spring.web.cors.allowed-headers=*
server.port=8081
